"use client";

import "../styles/fonts.css";

import { ChakraProvider } from "@chakra-ui/react";
import customTheme from "@/styles/customTheme";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider theme={customTheme}>{children} </ChakraProvider>
      </body>
    </html>
  );
}

