import pip
import os

try:
    import openai
except ImportError as e:
    pip.main(['install', 'openai'])
    import openai

openai.organization = "org-6SAh5dmJQDX58hxNwwyz24QZ"
openai.api_key = os.getenv("OPENAI-API-KEY")


def ai_request(request_text, tokens=1000) -> str:
    """
    Return the AI response generated by the OpenAI GPT-3 model.

    Parameters
    ----------
    request_text : str
        The user's request or question in string format.

    tokens : int, optional
        The maximum number of tokens (words) that the response can contain. Defaults to 2000.

    Returns
    -------
    str
        The AI-generated response in string format.
    """
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": "You are a health guidance figure helping a user live a healthy life."},
            {"role": "user", "content": f"{request_text}"},
        ],
        max_tokens=tokens
    )
    first_choice = 0
    text = response["choices"][first_choice]["message"]["content"]
    return text